jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run:| 
          mkdir dist
          echo "panda" > dist/panda.txt
      - name: Upload base ref info
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path:
            dist
          retention-days: 1
