name: pandabuild

on:
  push:
  #workflow_dispatch:

permissions:
  contents: read

jobs:
  panda-build-job:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3

      #ビルドに相当
      - name: panda create artifact
        run: |
          mkdir dist
          echo "panda" > dist/panda.txt
    # dist配下をartifact.zipとしてアップロードする
      - name: panda archive zip file
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./dist
