name: pandaDownload
on:
#  push:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  artifactdownload:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pandabuild.yml
          name: artifact
          workflow_conclusion: success
          
